default_platform(:ios)
opt_out_usage

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
DEVELOPER_EXTENSION_APP_IDENTIFIER = ENV["DEVELOPER_EXTENSION_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]
APP_NAME = ENV["APP_NAME"]
DEVELOPMENT_TEAM = ENV["DEVELOPMENT_TEAM"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

def create_app_config
  File.open("../Config.xcconfig", "w") do |f|
    f << <<~MULTILINE_STRING
    BUNDLE_IDENTIFIER = #{DEVELOPER_APP_IDENTIFIER}
    BUNDLE_IDENTIFIER_EXTENSION = #{DEVELOPER_EXTENSION_APP_IDENTIFIER}
    APP_NAME = #{APP_NAME}
    DEVELOPMENT_TEAM = #{DEVELOPMENT_TEAM}
    MULTILINE_STRING
  end
end

platform :ios do
  lane :create_app_config do
    create_app_config
  end

  lane :closed_beta do
    create_app_config
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false
    )

    increment_build_number(xcodeproj: "Redirector.xcodeproj")

    match(
      type: 'appstore',
      app_identifier: ["#{DEVELOPER_APP_IDENTIFIER}", "#{DEVELOPER_EXTENSION_APP_IDENTIFIER}"],
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    gym(
      configuration: "Release",
      workspace: "Redirector.xcodeproj/project.xcworkspace",
      scheme: "Redirector (iOS)",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      },
      xcargs: "-allowProvisioningUpdates",
      disable_xcpretty: true
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: false,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "Redirector.ipa"
    )

    delete_temp_keychain(keychain_name)
  end
end
